--조건에 맞는 사용자 정보 조회하기
WITH CTE AS (
    SELECT WRITER_ID, COUNT(*) AS CNT
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
)
SELECT U.USER_ID, NICKNAME,
    IF(STREET_ADDRESS2 IS NULL, CONCAT_WS(" ", CITY, STREET_ADDRESS1), CONCAT_WS(" ", CITY,STREET_ADDRESS1, STREET_ADDRESS2)) AS 전체주소,
    CONCAT_WS("-", LEFT(TLNO, 3), SUBSTRING(TLNO, 4, 4), RIGHT(TLNO, 4)) AS 전화번호
FROM USED_GOODS_USER AS U
WHERE (SELECT CNT FROM CTE AS C WHERE C.WRITER_ID = U.USER_ID) > 2
ORDER BY USER_ID DESC;