-- 자동차 대여 기록 별 대여 금액 구하기
SELECT 
    HISTORY_ID,
    IF(P.PLAN_ID IS NULL,
       DAILY_FEE*(DATEDIFF(H.END_DATE, H.START_DATE)+1),
       ROUND(DAILY_FEE*(DATEDIFF(H.END_DATE, H.START_DATE)+1)*(100 - P.DISCOUNT_RATE)/100, 0)) as FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as H
INNER JOIN CAR_RENTAL_COMPANY_CAR as C
ON H.CAR_ID = C.CAR_ID AND C.CAR_TYPE = "트럭"
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as P
ON C.CAR_TYPE = P.CAR_TYPE AND
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) BETWEEN 6 AND 28 THEN P.DURATION_TYPE = '7일 이상' 
            WHEN DATEDIFF(END_DATE, START_DATE) BETWEEN 29 AND 88 THEN P.DURATION_TYPE = '30일 이상' 
            WHEN DATEDIFF(END_DATE, START_DATE) >= 89 THEN P.DURATION_TYPE = '90일 이상'
        END
ORDER BY FEE DESC, HISTORY_ID DESC;